server:
  port: 8080

#Н2 временно для тестирования.
spring:
  datasource:
    url: jdbc:h2:mem:bankcards;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog-master.yaml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

app:
  jwt:
    access-token-secret: mySuperSecretAccessKeyForJWT123!!
    refresh-token-secret: mySuperSecretRefreshKeyForJWT789!!
    access-token-expiration: 10m
    refresh-token-expiration: 1h
  card-encryption:
    key: trainingKey12345